language: python
dist: bionic
python:
- 3.7
- 3.6
install: 
  - pip install -e .
script: pytest -v ./tests
deploy:
  - provider: pypi
    distributions: sdist bdist_wheel
    user: leigh-johnson
    on:
      tags: true
      repo: leigh-johnson/gym-donkeycar
      python: 3.6
      skip_cleanup: true
    password:
      secure: G0d0O73NLE7RRh++6LaoaYtJiJvGZbSl3aJYlEIO5B3ioVYDc6SsCnbeEDZmSO3+5/zDh5A98MRkPLPZQ+45eSgnZoJKgs02OrsaXxc0yRr+0TNcXgKoMXSPCwo4DEzN1XGAD/NpCFiG+ReGuBDFfd8hGw5m0DKKwXKix+AF8YQInFUwSYwG38A6I0PHLyLELZh5jMvDOTTjwosc1b6i3C5dhb8pwo3LHyZx3YqfZfKK2Fr3B/lsCFzYKnqKMFFJc/ugbpLUbJyDe+Q5jekKIgeNcDIKI4zFMKKeH9uc+x/2DmHMnQBQEWcdFp7IfnzqVCu3iaDFyGptk8COljwuyQMNk823vOOiHDnaNiY0ahPRS52Em/5SwNixKrG6RfZybHk4v5CbGAk5DEpq+Z7RxcHsRXD3ccsw+j/4pBbaCAxttaZVbUZ1ArsfFprrgDEmF/zTMb0vUVSJQOjsMLEb3zd5YDSe4Xb2tqhnylDXE2sYK9J1Y1SNf2dYLfmrADonoPM+MAIGpmZ/9CLGAxyzfoAkqmgDahX0EIsXmk+PqeSgoPVE/OK1PUeFwcY8bSNbOACv3l5sJUtY7YoZi3OUGXle6SMqbZSK5w1Rtiy7w9LT8HgDFh5Jpk9t8gqT/lLrUtKIQk9onCq+5xrS8W7gFHcyPjmt1MfIF1WI2xK/qx4=